# Generated by Django 4.1.5 on 2023-01-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0002_alter_dmatsaccount_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmatsaccount',
            old_name='owner',
            new_name='user',
        ),
    ]
