# Generated by Django 4.1.5 on 2023-01-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0010_alter_dmatsaccount_user_alter_share_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
    ]
