# Generated by Django 4.1.5 on 2023-01-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0014_share_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
    ]
